<?php
/**
 * vietnam_address.php
 * Dữ liệu cứng 63 tỉnh / thành phố Việt Nam và các phường/xã/thị trấn đại diện.
 * Trả về: $VN_ADDRESS['Tên tỉnh'] = ['Phường/Xã 1', 'Phường/Xã 2', ...]
 */

$VN_ADDRESS = [
    'An Giang' => ['Mỹ Bình','Mỹ Long','Mỹ Xuyên','Bình Khánh','Mỹ Hòa','Mỹ Phước','Mỹ Quý','Mỹ Thạnh','Đông Xuyên','Mỹ Thới'],
    'Bà Rịa - Vũng Tàu' => ['Phước Trung','Long Toàn','Long Hương','Phước Hưng','Kim Dinh','Hòa Long','Long Phước','Châu Pha','Tân Hải','Tân Phước'],
    'Bắc Giang' => ['Dĩnh Kế','Dĩnh Trì','Đa Mai','Hoàng Văn Thụ','Lê Lợi','Mỹ Độ','Ngô Quyền','Song Mai','Thọ Xương','Trần Phú'],
    'Bắc Kạn' => ['Đức Xuân','Huyền Tụng','Nguyễn Thị Minh Khai','Phùng Chí Kiên','Sông Cầu'],
    'Bạc Liêu' => ['1','2','3','5','7','Hiệp Thành','Nhà Mát','Vĩnh Trạch','Vĩnh Trạch Đông'],
    'Bắc Ninh' => ['Đại Phúc','Đáp Cầu','Khắc Niệm','Kinh Bắc','Ninh Xá','Phong Khê','Suối Hoa','Thị Cầu','Vân Dương','Vũ Ninh'],
    'Bến Tre' => ['An Hội','Phú Khương','Phú Tân','Tân Thạnh','Bình Phú','Mỹ Thạnh An','Phường 1','Phường 2','Phường 3','Phường 4'],
    'Bình Định' => ['Bùi Thị Xuân','Đống Đa','Ghềnh Ráng','Hải Cảng','Lê Hồng Phong','Lê Lợi','Ngô Mây','Nhơn Bình','Nhơn Phú','Quang Trung'],
    'Bình Dương' => ['Chánh Mỹ','Chánh Nghĩa','Định Hòa','Hiệp An','Hiệp Thành','Phú Cường','Phú Hòa','Phú Lợi','Phú Mỹ','Tân An'],
    'Bình Phước' => ['An Lộc','Hưng Chiến','Phú Thịnh','Phú Đức','Tân Thiện','Tân Xuân','Tiến Thành','Tiến Thành','Đồng Tiến','Đồng Tâm'],
    'Bình Thuận' => ['Bình Hưng','Đức Long','Đức Nghĩa','Đức Thắng','Hải Tiến','Hàm Tiến','Lạc Đạo','Mũi Né','Phú Hài','Phú Tài'],
    'Cà Mau' => ['1','2','4','5','6','7','8','9','An Xuyên','Tân Thành'],
    'Cần Thơ' => ['An Bình','An Hòa','An Khánh','An Nghiệp','Bình Thủy','Cái Khế','Hưng Lợi','Long Hòa','Long Hưng','Tân An'],
    'Cao Bằng' => ['Duyệt Trung','Hòa Chung','Hợp Giang','Ngọc Xuân','Sông Hiến','Sông Bằng','Tân Giang','Tân Thành','Đề Thám','Vĩnh Quang'],
    'Đà Nẵng' => ['An Hải Bắc','An Hải Đông','An Hải Tây','Bình Hiên','Bình Thuận','Hòa An','Hòa Cường Bắc','Hòa Cường Nam','Hòa Khê','Hòa Phát'],
    'Đắk Lắk' => ['An Lạc','Ea Tam','Khánh Xuân','Tân An','Tân Hòa','Tân Lập','Tân Lợi','Tân Thành','Thắng Lợi','Thống Nhất'],
    'Đắk Nông' => ['Đắk Nia','Nghĩa Thành','Nghĩa Trung','Quảng Thành','Thuận An'],
    'Điện Biên' => ['Him Lam','Mường Thanh','Nam Thanh','Noong Bua','Tân Thanh','Thanh Bình','Thanh Trường'],
    'Đồng Nai' => ['Bình Đa','Hòa Bình','Long Bình','Long Bình Tân','Phước Tân','Quyết Thắng','Tam Hiệp','Tam Hòa','Tân Biên','Tân Hiệp'],
    'Đồng Tháp' => ['1','2','3','4','6','11','Hòa Thuận','Mỹ Phú','Tân Quy Đông','Tân Quy Tây'],
    'Gia Lai' => ['Chi Lăng','Diên Hồng','Đống Đa','Hoa Lư','Hội Phú','Hội Thương','Ia Kênh','Phù Đổng','Thắng Lợi','Trà Bá'],
    'Hà Giang' => ['Minh Khai','Ngọc Hà','Nguyễn Trãi','Quang Trung','Trần Phú'],
    'Hà Nam' => ['Châu Sơn','Lam Hạ','Liêm Chính','Minh Khai','Quang Trung','Thanh Châu','Thanh Tuyền','Trần Hưng Đạo','Hai Bà Trưng','Lê Hồng Phong'],
    'Hà Nội' => ['Ba Đình','Cầu Giấy','Đống Đa','Hà Đông','Hai Bà Trưng','Hoàn Kiếm','Hoàng Mai','Long Biên','Nam Từ Liêm','Tây Hồ','Thanh Xuân','Bắc Từ Liêm'],
    'Hà Tĩnh' => ['Bắc Hà','Đại Nài','Nam Hà','Nguyễn Du','Tân Giang','Thạch Linh','Thạch Quý','Trần Phú','Văn Yên'],
    'Hải Dương' => ['Ái Quốc','Bình Hàn','Cẩm Thượng','Hải Tân','Lê Thanh Nghị','Nam Đồng','Nhị Châu','Ngọc Châu','Nguyễn Trãi','Phạm Ngũ Lão','Quang Trung','Tân Bình','Thanh Bình','Tứ Minh','Việt Hòa'],
    'Hải Phòng' => ['An Biên','Cầu Đất','Cầu Tre','Dư Hàng Kênh','Đằng Giang','Đằng Lâm','Đông Khê','Hồ Nam','Hùng Vương','Lam Sơn','Lê Chân','Máy Chai','Nghĩa Xá','Niệm Nghĩa','Phạm Ngũ Lão'],
    'Hậu Giang' => ['1','3','4','5','7','Hiệp Thành','Minh Tân','Ngã Bảy','Tân Phú','Vị Tân'],
    'Hòa Bình' => ['Chăm Mát','Dân Chủ','Đồng Tiến','Hữu Nghị','Kỳ Sơn','Phương Lâm','Quỳnh Lâm','Tân Thịnh','Thái Bình','Thịnh Lang'],
    'TP Hồ Chí Minh' => ['Bến Nghé','Bến Thành','Bình Thuận','Cầu Kho','Cầu Ông Lãnh','Cô Giang','Đa Kao','Nguyễn Cư Trinh','Nguyễn Thái Bình','Phạm Ngũ Lão'],
    'Hưng Yên' => ['An Tảo','Bảo Khê','Hiến Nam','Hồng Châu','Hồng Nam','Lam Sơn','Lê Lợi','Minh Khai','Nhân Hòa','Quang Trung'],
    'Khánh Hòa' => ['Lộc Thọ','Phương Sài','Phương Sơn','Phước Hòa','Phước Tân','Phước Tiến','Tân Lập','Vĩnh Hải','Vĩnh Hòa','Vĩnh Nguyên','Vĩnh Thọ','Vĩnh Trường','Xương Huân'],
    'Kiên Giang' => ['An Bình','Dương Đông','Rạch Sỏi','Vĩnh Bảo','Vĩnh Lạc','Vĩnh Lợi','Vĩnh Quang','Vĩnh Thanh','Vĩnh Thông'],
    'Kon Tum' => ['Duy Tân','Lê Lợi','Ngô Mây','Nguyễn Trãi','Quyết Thắng','Thắng Lợi','Thống Nhất','Trần Hưng Đạo','Trường Chinh'],
    'Lai Châu' => ['Đoàn Kết','Đông Phong','Quyết Thắng','Quyết Tiến','San Thàng','Tân Phong'],
    'Lâm Đồng' => ['1','2','3','4','5','6','7','8','9','10','11','12'],
    'Lạng Sơn' => ['Chi Lăng','Đông Kinh','Hoàng Văn Thụ','Tam Thanh','Tân Thành','Vĩnh Trại'],
    'Lào Cai' => ['Bắc Cường','Bắc Lệnh','Cam Đường','Cốc Lếu','Duyên Hải','Kim Tân','Lào Cai','Nam Cường','Pom Hán','Thống Nhất'],
    'Long An' => ['1','2','3','4','5','6','7','Bình Tâm','Hậu Thạnh Đông','Khánh Hậu'],
    'Nam Định' => ['Bà Triệu','Cửa Bắc','Cửa Nam','Hạ Long','Lộc Hạ','Lộc Vượng','Lộc Hòa','Mỹ Xá','Năng Tĩnh','Ngô Quyền','Nguyễn Du','Quang Trung','Thống Nhất','Trần Đăng Ninh','Trần Hưng Đạo','Trần Tế Xương','Trường Thi','Văn Miếu','Vỵ Hoàng'],
    'Nghệ An' => ['Bến Thủy','Cửa Nam','Đông Vĩnh','Đội Cung','Hà Huy Tập','Hưng Bình','Hưng Dũng','Hưng Phúc','Lê Lợi','Lê Mao','Lê Viết Thuật','Nghi Phú','Quán Bàu','Quang Trung','Trung Đô'],
    'Ninh Bình' => ['Bích Đào','Đông Thành','Nam Bình','Nam Thành','Ninh Khánh','Ninh Phong','Ninh Sơn','Phúc Thành','Tân Thành','Thanh Bình'],
    'Ninh Thuận' => ['Đạo Long','Đô Vinh','Kinh Dinh','Mỹ Bình','Mỹ Đông','Mỹ Hải','Mỹ Hương','Mỹ Sơn','Phủ Hà','Phước Mỹ','Thanh Sơn','Tấn Tài'],
    'Phú Thọ' => ['Bạch Hạc','Bến Gót','Dữu Lâu','Gia Cẩm','Minh Phương','Nông Trang','Phượng Lâu','Tân Dân','Thanh Miếu','Tiên Cát','Vân Cơ','Vân Phú'],
    'Phú Yên' => ['1','2','3','4','5','6','7','8','9','Bình Kiến','Bình Ngọc','Phú Đông','Phú Lâm'],
    'Quảng Bình' => ['Bắc Lý','Bắc Nghĩa','Đồng Mỹ','Đồng Phú','Đồng Sơn','Hải Đình','Hải Thành','Nam Lý','Phú Hải','Quảng Long'],
    'Quảng Nam' => ['An Mỹ','An Phú','An Sơn','Cẩm An','Cẩm Châu','Cẩm Nam','Cẩm Phô','Cẩm Thanh','Minh An','Sơn Phong','Tân An','Thanh Hà'],
    'Quảng Ngãi' => ['Chánh Lộ','Lê Hồng Phong','Nghĩa Chánh','Nghĩa Dũng','Nghĩa Lộ','Nguyễn Nghiêm','Quảng Phú','Trần Hưng Đạo','Trần Phú'],
    'Quảng Ninh' => ['Bãi Cháy','Cao Thắng','Cao Xanh','Đại Yên','Giếng Đáy','Hà Khánh','Hà Lầm','Hà Phong','Hà Trung','Hà Trung','Hồng Gai','Hùng Thắng','Hồng Hà','Hồng Hải','Tuần Châu','Việt Hưng','Yết Kiêu'],
    'Quảng Trị' => ['1','2','3','4','5','Đông Lễ','Đông Lương','Đông Thanh','Đông Thành','Nam Đông'],
    'Sóc Trăng' => ['1','2','3','4','5','6','7','8','9','10'],
    'Sơn La' => ['Chiềng An','Chiềng Cơi','Chiềng Lề','Chiềng Ngần','Chiềng Sinh','Chiềng Xôm','Quyết Thắng','Quyết Tâm','Tô Hiệu'],
    'Tây Ninh' => ['1','2','3','4','Hiệp Ninh','Ninh Sơn','Ninh Thạnh'],
    'Thái Bình' => ['Bồ Xuyên','Đề Thám','Hoàng Diệu','Kỳ Bá','Lê Hồng Phong','Phú Khánh','Tiền Phong','Trần Hưng Đạo','Trần Lãm','Vũ Phúc','Vũ Tiến'],
    'Thái Nguyên' => ['Cam Giá','Đồng Bẩm','Đồng Quang','Gia Sàng','Hoàng Văn Thụ','Hương Sơn','Phan Đình Phùng','Phú Xá','Quang Trung','Quang Vinh','Tân Lập','Tân Thịnh','Thịnh Đán','Trung Thành','Túc Duyên'],
    'Thanh Hóa' => ['An Hưng','Ba Đình','Điện Biên','Đông Cương','Đông Hải','Đông Hương','Đông Sơn','Đông Thọ','Hàm Rồng','Lam Sơn','Long Anh','Nam Ngạn','Ngọc Trạo','Phú Sơn','Quảng Cát','Quảng Đông','Quảng Hưng','Quảng Thịnh','Quảng Vinh','Tào Xuyên','Thiệu Dương','Thiệu Khánh','Thiệu Vân','Trung Sơn'],
    'Thừa Thiên Huế' => ['An Cựu','An Đông','An Hòa','An Tây','Đông Ba','Gia Hội','Hương Long','Hương Sơ','Kim Long','Phú Bình','Phú Cát','Phú Hiệp','Phú Hòa','Phú Hội','Phú Nhuận','Phú Thuận','Phường Đúc','Tây Lộc','Thuận Hòa','Thuận Lộc','Thuận Thành','Trường An','Vỹ Dạ','Xuân Phú'],
    'Tiền Giang' => ['1','2','3','4','5','6','7','8','9','10'],
    'Trà Vinh' => ['1','2','3','4','5','6','7','8','9'],
    'Tuyên Quang' => ['An Tường','Đội Cấn','Hưng Thành','Lưỡng Vượng','Minh Xuân','Mỹ Lâm','Nông Tiến','Tân Hà','Tràng Đà','Ỷ La'],
    'Vĩnh Long' => ['1','2','3','4','5','8','9','Đông Thuận','Tân Hạnh','Tân Hòa'],
    'Vĩnh Phúc' => ['Đồng Tâm','Đống Đa','Hội Hợp','Khai Quang','Liên Bảo','Ngô Quyền'],
    'Yên Bái' => ['Đồng Tâm','Hồng Hà','Minh Tân','Nam Cường','Nguyễn Phúc','Nguyễn Thái Học','Tuy An','Yên Ninh','Yên Thịnh'],
];
